### ISSUE TITLE
Not atomic Redis operations

### ISSUE THREAD

**Issue by ksysoev** [officer47p/guardians-of-the-cluster#1]
Hi :) good work, just few small suggestions.

1) I don't see where you set ttl on Redis keys. If we do rate limiting it's usually within some time period.
2) don't use get/set when you deal with concurrency, when multiple concurrent requests will hit your server you will be miscalculating requests counter try to use combination of:

- Set+NX+EX to start measuring interval
- Inc to increment and get current value of the counter.

Both operations should be done within single Redis transaction

**Comment by officer47p** [comment]
Hey @ksysoev, happy to see you here and thanks for your code review ❤️ 

Regarding the mentioned points:
1. There is a scheduled reset cycle at [line 36](https://github.com/officer47p/guardians-of-the-cluster/blob/ef8cc32f74fdaf4b7e4a17bf37f73179e0ae1670/main.go#L36C1-L36C1) that removes all keys from the cache. However, it might cause some serious issues when there are multiple instances of the rate-limiter deployed.
2. Using a single transaction when getting a value and manipulating it seems like a good idea, but I'm wondering if the reset cycle goroutine can do the key cleanup part, without us needing to set ttl for the keys 🤔

**Comment by ksysoev** [comment]
1) IMHO you shouldn't do scheduled flushing of Redis keys. imagine you will have longer time intervals for measuring. in this case your clients will be able to exceed your rate limitation if they start sending requests close to the end of the interval and then you reset and they again can send requests. basically, in a short period of time, they can double a quota. Measuring intervals should start individually for each client as soon as you receive the first request. You don't need to garbage collect or flush keys, Redis can do it for you, just use TTL.

2)the idea to have something like this:

```
multi
set my_key 0 NX EX 10
INCR my_key 1
exec
```
The first command only will be executed if the key does not exist. responsibility of it just to start measuring intervals for particular clients.


Also, keep in mind that it could be common to have different measuring intervals
for example, we allow 10 login attempts in a minute and only 30 login attempts in 10 minutes, it's needed to provide a better user experience and still keep good security.
